language: php

sudo: false

env:
  global:
    - secure: "bjblntH+I3jBerh9RTqaigFrK8VeTwyk90X6tG2uDzp4cM/FC7/VfCtniUkyQiC2ZZu3gIrfRSDEi4co9Y8LJ1HpNj9KuHud2lQWv7GXiaC0So4H1/izxQApYoVInoEtfJ88qNYhJNtBg80s4bg22TOwcVjXRG+1URcLDwD4m4fuCefwhwwgsLor+1G5FXPrjQWjR+gOeTMd0S5ZoKHZJ73FDCN0KEt8A4+GBLku6EDDC/y/o28phkEgknV5CJcLlgeIjq697jOHgRRHSWNXox2F3rPqXvjbPnYXvTc8LgHzNhv3zlsgqtbJmYrCFNUL9vG13wDnawNBStqZuszrpxgHQYtwA6WOU+ZTWgeZZI+SfDAuOopSfeHyovTx6CEbSvpcaBoEB7ggO65eczPnAMm3Mit89RrzR6GSrViqgmOj4xNs4HmrPApt7y1b8w5oBzXU71WYB24vUGTrobhNnwDkPcS1QJmH7jH9gqlUwFuCBfk2GVMA+ZGYGkNShsUYKxgwTugspdrFPvg416b7sWW5DG1KVLvlP6eDQamK88G+KifBtjlCFzf+jZA/Sb1u6ZpJ7rYtT/t+C5uaBoh31WP2a4YJFdDbG2KiOBjujBKKNcRMZLSwq7cPfVPaVwoFNbI7KOj0s9ql7tVsMCofwlZjv+Sey7v2OfpEESMdHfg="
    - secure: "HcWRPoPCTJNQCAo+asQrPWifsJmT318mWyfU1/nsSPKpOK7gthZlKWji2Tjjd03bJDEk7NRvxVb/B05yIWNT8ai6nogfu8nAO4HVFnpMH890XF4U0lqNPcEqfh22IgjjGT2tEhUpUygpUQ69uhhgJzMx7ImRCJpYfGbLFhpxob3OzFyIt5fQ25K9bqw0hDxn2vpdMuYUYXhcOyeHWbQomv+/V15weyCVmbiZVkl+wyYnFXEWdq2uoZnM/aE6I7MgderWmgxI3Nu6oYruwSH4bLqDV07lvy33sVK6tTD+TWyu+IqQ28DEEdWrd0kuQhuNcA5Tjx0xUaIHBTg61nOkxTSaZToy79aMlPhZFu+BLgJIWsP3pREylPE/W5e+DHsWpBVaCtbjot1pAP3rc8zFXM/Zn7PlI19a+z5SFkig2Jqg7FT7dSfqT+U9VSxhZFBjiroj0en3bFzoFmkq1SbLw7sOjHjyj4/fbFYZEQR7f2JcLXOy0CaB3QYtpjk+WMXLk5ETtseBm9zUQ2+H8DAxJVE4zBfgdj92PMoWkXnleDOwgg7IJsZk1+Gx+Xg3L9Zvj4bLrOB7kTmxliwCVjFFqVqaAPOm2IPMZ4Uxs18U+UE4l8SNcXTFZxVNGa1SAXGwVALBy0NSjCemQ4fkSd23FCP4nLrvqiM5OyzW7Il79+w="

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: WITH_LOWEST=true
    - php: 5.6
      env: WITH_HIGHEST=true WITH_CS=true
    - php: 7.0
      env: WITH_LOWEST=true
    - php: 7.0
      env: WITH_HIGHEST=true
    - php: 7.1
      env: WITH_LOWEST=TRUE
    - php: 7.1
      env: WITH_HIGHEST=true WITH_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - if [[ "$WITH_COVERAGE" != "true" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest; else composer update; fi

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - mkdir -p build/logs

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=phpunit.xml; fi
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

notifications:
  email: false
